function spec_write_subject_summary_csv(outPath, subjid, tvi, gaRcl, logf)
% SPEC_WRITE_SUBJECT_SUMMARY_CSV  Write one subject-level summary row to CSV
% V 1.1.0
%
% Pure writer — no statistics are computed here.  All inputs must be
% pre-computed by the appropriate helpers before calling this function:
%
%   tvi   = spec_compute_tvi_alpha(featGA.bi_pre, logf)
%   gaRcl = spec_compute_ga_rcl(rclTable, logf)
%
% Rows are appended so that all subjects accumulate in a single CSV across
% a batch run.  The header is written only on the first subject (i.e. when
% the file does not yet exist).
%
% Inputs:
%   outPath : full path to the output CSV
%   subjid  : integer subject ID
%   tvi     : struct from spec_compute_tvi_alpha
%               .tvi_alpha, .mssd_bi_pre, .var_bi_pre, .n_trials_bi
%   gaRcl   : struct from spec_compute_ga_rcl
%               .ga_phase_r_cl, .ga_phase_p_perm, .n_chans_r_cl
%   logf    : (optional) MATLAB log file handle

if nargin < 5, logf = 1; end

T = table( ...
    int32(subjid),           ...
    int32(tvi.n_trials_bi),  ...
    tvi.tvi_alpha,           ...
    tvi.mssd_bi_pre,         ...
    tvi.var_bi_pre,          ...
    gaRcl.ga_phase_r_cl,     ...
    gaRcl.ga_phase_p_perm,   ...
    int32(gaRcl.n_chans_r_cl), ...
    'VariableNames', { ...
        'subjid',            ...
        'n_trials_bi',       ...
        'tvi_alpha',         ...
        'mssd_bi_pre',       ...
        'var_bi_pre',        ...
        'ga_phase_r_cl',     ...
        'ga_phase_p_perm',   ...
        'n_chans_r_cl'       ...
    } ...
);

if exist(outPath, 'file')
    writetable(T, outPath, 'WriteMode', 'append', 'WriteVariableNames', false);
else
    writetable(T, outPath);
end

spec_logmsg(logf, '[SUBJ_SUM] Written -> %s', outPath);
end